package qlbanhang;

import java.awt.Color;
import java.awt.event.ItemEvent;
import java.io.File;
import java.util.*;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import sun.util.calendar.CalendarUtils;
/**
 *
 * @author TGDD
 */
public class QLBanHang extends javax.swing.JFrame {

    /**
     * Creates new form QLBanHang
     */
    private DanhSachBanHang a = new DanhSachBanHang();
    DefaultTableModel model = new DefaultTableModel();
    int r;
    public QLBanHang() {
        initComponents();
        jTable1.setModel(model);
        model.addColumn("Mặt hàng");
        model.addColumn("Mã");
        model.addColumn("Tên hàng");
        model.addColumn("Màu");
        model.addColumn("Loại");
        model.addColumn("Năm sx");
        model.addColumn("Số lượng");
        model.addColumn("Đơn giá");
        model.addColumn("Giảm Giá");
        model.addColumn("Thành Tiền");
        try {
            File f = new File("input.txt");
            if(f.exists()){
                Scanner read = new Scanner(f);
                while(read.hasNext()){
                    Scanner kb = new Scanner(read.nextLine());
                    String ma="",ten="",mau="",loai="",mh="";
                    int nam,sl,dg;
                    ma=kb.next();
                    while(!kb.hasNextInt()) ten=ten+kb.next()+" ";
                    nam=kb.nextInt();
                    while(!kb.hasNextInt()) mau=mau+kb.next()+" ";
                    sl=kb.nextInt();
                    while(!kb.hasNextInt()) loai=loai+kb.next()+" ";
                    dg=kb.nextInt();
                    while(kb.hasNext()) mh=mh+kb.next()+" ";
                    DienTu x;
                    if(mh=="ĐIỆN THOẠI"){
                         x = new DienThoai(mh,ma,ten,mau,loai,nam,sl,dg);
                    }else x = new Laptop(mh,ma,ten,mau,loai,nam,sl,dg);
                    a.nhap(x);
                     model.addRow(new Object[]{x.getMh(),
            x.getMa(),x.getTen(),x.getMau(),x.getLoai(),x.getNam(),x.getSoLuong(),x.getDonGia(),x.giamGia(),x.thanhTien()});
                }
            }else System.out.println("Khong ton tai file");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    txt_ck.setText(""+a.tongTienGiam());
    txt_sumSL.setText(""+a.tongSoLuong());
    txt_sum.setText(""+a.tongTien());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txt_ma = new javax.swing.JTextField();
        txt_ten = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_mau = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cbx_loai = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        cbx_nam = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txt_sl = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_dg = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cbx_mh = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton_add = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txt_ck = new javax.swing.JTextField();
        jButton_delete = new javax.swing.JButton();
        jButton_update = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        txt_sumSL = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txt_sum = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jButton_refresh = new javax.swing.JButton();
        jButton_exit = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        txt_matk = new javax.swing.JTextField();
        jButton_find = new javax.swing.JButton();
        jButton_xoaTim = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jButton_save = new javax.swing.JButton();
        jButton_mo = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 204));
        jLabel3.setText("Mã");

        txt_ma.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_ma.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_maKeyPressed(evt);
            }
        });

        txt_ten.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_ten.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_tenKeyPressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 204));
        jLabel4.setText("Tên SP");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 204));
        jLabel5.setText("Màu");

        txt_mau.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_mau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_mauActionPerformed(evt);
            }
        });
        txt_mau.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_mauKeyPressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 204));
        jLabel6.setText("Loại");

        cbx_loai.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbx_loai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gaming", "Đồ hoạ", "Văn phòng", "Cục gạch", "Smartphone", " " }));
        cbx_loai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_loaiActionPerformed(evt);
            }
        });
        cbx_loai.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbx_loaiKeyPressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 204));
        jLabel7.setText("Năm SX");

        cbx_nam.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cbx_nam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035", "2036", "2037", "2038", "2039", "2040", "2041", "2042", "2043", "2044", "2045", "2046", "2047", "2048", "2049", "2050", "2051", "2052", "2053", "2054", "2055", "2056", "2057", "2058", "2059", "2060", "2061", "2062", "2063", "2064", "2065", "2066", "2067", "2068", "2069", "2070", "2071", "2072", "2073", "2074", "2075", "2076", "2077", "2078", "2079", "2080", "2081", "2082", "2083", "2084", "2085", "2086", "2087", "2088", "2089", "2090", "2091", "2092", "2093", "2094", "2095", "2096", "2097", "2098", "2099", "2100", " " }));
        cbx_nam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_namActionPerformed(evt);
            }
        });
        cbx_nam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbx_namKeyPressed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 204));
        jLabel9.setText("Số lượng");

        txt_sl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_sl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_slKeyPressed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 51, 204));
        jLabel10.setText("Đơn giá");

        txt_dg.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_dg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_dgKeyPressed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 51, 204));
        jLabel11.setText("VND");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 51, 204));
        jLabel12.setText("Mặt hàng");

        cbx_mh.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbx_mh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ĐIỆN THOẠI", "LAPTOP" }));
        cbx_mh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_mhActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 51, 204));
        jLabel22.setText("ĐVT");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(txt_ten, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_ma, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(cbx_nam, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(71, 71, 71))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_mau, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbx_loai, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txt_sl, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel22))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txt_dg, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11))
                    .addComponent(cbx_mh, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_sl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_dg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_ma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(cbx_nam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_ten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txt_mau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(cbx_mh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(cbx_loai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 51));
        jLabel2.setText("Thông tin");

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 153, 51));
        jLabel8.setText("Chi tiết bán hàng");

        jTable1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 102), new java.awt.Color(0, 153, 102), new java.awt.Color(0, 153, 102), new java.awt.Color(0, 153, 102)));
        jTable1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton_add.setBackground(new java.awt.Color(0, 153, 51));
        jButton_add.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_add.setForeground(new java.awt.Color(255, 255, 255));
        jButton_add.setText("Nhập");
        jButton_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_addActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 51, 204));
        jLabel13.setText("Tổng tiền chiết khấu ");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 51, 204));
        jLabel14.setText("VND");

        txt_ck.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_ck.setForeground(new java.awt.Color(255, 0, 0));
        txt_ck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ckActionPerformed(evt);
            }
        });

        jButton_delete.setBackground(new java.awt.Color(0, 153, 51));
        jButton_delete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_delete.setForeground(new java.awt.Color(255, 255, 255));
        jButton_delete.setText("Xoá");
        jButton_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_deleteActionPerformed(evt);
            }
        });

        jButton_update.setBackground(new java.awt.Color(0, 153, 51));
        jButton_update.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_update.setForeground(new java.awt.Color(255, 255, 255));
        jButton_update.setText("Cập nhật");
        jButton_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_updateActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 51, 204));
        jLabel16.setText("Tổng số lượng ");

        txt_sumSL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_sumSL.setForeground(new java.awt.Color(255, 0, 0));
        txt_sumSL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_sumSLActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 51, 204));
        jLabel17.setText("Tổng thành tiền");

        txt_sum.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_sum.setForeground(new java.awt.Color(255, 0, 0));
        txt_sum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_sumActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 51, 204));
        jLabel18.setText("VND");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 51, 204));
        jLabel19.setText("ĐVT");

        jButton_refresh.setBackground(new java.awt.Color(0, 153, 51));
        jButton_refresh.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_refresh.setForeground(new java.awt.Color(255, 255, 255));
        jButton_refresh.setText("Làm mới");
        jButton_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_refreshActionPerformed(evt);
            }
        });

        jButton_exit.setBackground(new java.awt.Color(0, 153, 51));
        jButton_exit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_exit.setForeground(new java.awt.Color(255, 255, 255));
        jButton_exit.setText("Thoát");
        jButton_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_exitActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(153, 153, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 51, 204));
        jLabel21.setText("Mã");

        txt_matk.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jButton_find.setBackground(new java.awt.Color(0, 153, 51));
        jButton_find.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_find.setForeground(new java.awt.Color(255, 255, 255));
        jButton_find.setText("Tìm Kiếm");
        jButton_find.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_findActionPerformed(evt);
            }
        });

        jButton_xoaTim.setBackground(new java.awt.Color(0, 153, 51));
        jButton_xoaTim.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_xoaTim.setForeground(new java.awt.Color(255, 255, 255));
        jButton_xoaTim.setText("Xoá Tìm ");
        jButton_xoaTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_xoaTimActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txt_matk, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_xoaTim, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_find, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txt_matk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_find))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_xoaTim))
        );

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 153, 51));
        jLabel20.setText("Tìm Kiếm");

        jButton_save.setBackground(new java.awt.Color(0, 153, 51));
        jButton_save.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_save.setForeground(new java.awt.Color(255, 255, 255));
        jButton_save.setLabel("Lưu");
        jButton_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_saveActionPerformed(evt);
            }
        });

        jButton_mo.setBackground(new java.awt.Color(0, 153, 51));
        jButton_mo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_mo.setForeground(new java.awt.Color(255, 255, 255));
        jButton_mo.setText("Mở File");
        jButton_mo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_moActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(0, 153, 153));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel23.setText("QUẢN LÝ THIẾT BỊ ĐIỆN TỬ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(344, 344, 344)
                .addComponent(jLabel23)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton_mo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jButton_refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jButton_update, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jButton_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jButton_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(328, 328, 328)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addGap(104, 104, 104))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 969, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(295, 295, 295)
                        .addComponent(jLabel8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel16)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txt_sumSL, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel13)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txt_ck, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton_add, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(jButton_save, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel19))
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17)
                        .addGap(23, 23, 23)
                        .addComponent(txt_sum, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel18)
                        .addGap(3, 3, 3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel20))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addGap(13, 13, 13)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(txt_ck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(txt_sum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txt_sumSL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_add)
                    .addComponent(jButton_update)
                    .addComponent(jButton_refresh)
                    .addComponent(jButton_exit)
                    .addComponent(jButton_delete)
                    .addComponent(jButton_save)
                    .addComponent(jButton_mo))
                .addContainerGap(702, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_mauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_mauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_mauActionPerformed

    private void cbx_loaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_loaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_loaiActionPerformed

    private void cbx_namActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_namActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_namActionPerformed

    private void cbx_mhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_mhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_mhActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        r = jTable1.getSelectedRow();
        TableModel model1 = jTable1.getModel();
        if(r>=0){
            String ma = (String) jTable1.getValueAt(r, 1);
            for(int i=0;i<a.size();i++)
            if(ma.equals(a.get(i).ma)){
                txt_ma.setText(ma);
                cbx_loai.setSelectedItem(a.get(i).getLoai());
                cbx_mh.setSelectedItem(a.get(i).getMh());
                txt_ten.setText(a.get(i).getTen());
                txt_mau.setText(a.get(i).getMau());
                cbx_nam.setSelectedItem(""+a.get(i).getNam());
                txt_sl.setText(""+a.get(i).getSoLuong());
                txt_dg.setText(""+a.get(i).getDonGia());
            }
        }
        String mh = model1.getValueAt(r, 0).toString();
        switch(mh){
            case "ĐIỆN THOẠI ":
                cbx_mh.setSelectedIndex(0);
                break;
            case "LAPTOP ":
                cbx_mh.setSelectedIndex(1);
                break;    
        }
        String loai = model1.getValueAt(r, 4).toString();
        switch(loai){
            case "Gaming ":
                cbx_loai.setSelectedIndex(0);
                break;
            case "Đồ hoạ ":
                cbx_loai.setSelectedIndex(1);
                break;    
            case "Văn phòng ":
                cbx_loai.setSelectedIndex(2);
                break;
            case "Cục gạch ":
                cbx_loai.setSelectedIndex(3);
                break; 
            case "Smartphone ":
                cbx_loai.setSelectedIndex(4);
                break;     
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_addActionPerformed
        // TODO add your handling code here:
        DienTu x ;
        String ma, ten, mau, loai,mh;
        int nam,soLuong, donGia;
        StringBuilder sb = new StringBuilder();
        if(txt_ma.getText().equals("")){
            sb.append("Mã không được để trống \n");
            txt_ma.setBackground(Color.red);
        }else txt_ma.setBackground(Color.white);
        if(txt_ten.getText().equals("")){
            sb.append("Tên không được để trống \n");
            txt_ten.setBackground(Color.red);
        }else txt_ten.setBackground(Color.white);
        if(txt_mau.getText().equals("")){
            sb.append("Màu không được để trống \n");
            txt_mau.setBackground(Color.red);
        }else txt_mau.setBackground(Color.white);
        if(txt_sl.getText().equals("")){
            sb.append("Số lượng không được để trống \n");
            txt_sl.setBackground(Color.red);
        }else txt_sl.setBackground(Color.white);
        if(txt_dg.getText().equals("")){
            sb.append("Đơn giá không được để trống \n");
            txt_dg.setBackground(Color.red);
        }else txt_dg.setBackground(Color.white);
        if(sb.length()>0){
            JOptionPane.showMessageDialog(this, sb.toString(), "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        ma = txt_ma.getText();
        ten = txt_ten.getText();
        mau = txt_mau.getText();
        nam = Integer.parseInt(""+cbx_nam.getSelectedIndex());
        loai = (String)(cbx_loai.getSelectedItem());
        soLuong = Integer.parseInt(txt_sl.getText());
        donGia = Integer.parseInt(txt_dg.getText());
        mh=(String) cbx_mh.getSelectedItem();
        if(cbx_mh.getSelectedItem()=="ĐIỆN THOẠI"){
            x = new DienThoai(mh,ma,ten,mau,loai,nam,soLuong,donGia);
        }
        else x = new Laptop(mh,ma,ten,mau,loai,nam,soLuong,donGia);
        a.nhap(x);
        model.addRow(new Object[]{x.getMh(),
            x.getMa(),x.getTen(),x.getMau(),x.getLoai(),x.getNam(),x.getSoLuong(),x.getDonGia(),x.giamGia(),x.thanhTien()});
    JOptionPane.showMessageDialog(this, "Nhập thành công","Thông báo",WIDTH);
    txt_ck.setText(""+a.tongTienGiam());
    txt_sumSL.setText(""+a.tongSoLuong());
    txt_sum.setText(""+a.tongTien());

    }//GEN-LAST:event_jButton_addActionPerformed

    private void txt_ckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ckActionPerformed

    private void jButton_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_deleteActionPerformed
        // TODO add your handling code here:
        int index = jTable1.getSelectedRow();
        if(index==-1){
            JOptionPane.showMessageDialog(this, "Vui lòng chọn 1 hàng để xoá","Thông báo",JOptionPane.ERROR_MESSAGE);
            return;
        }
        int choice = JOptionPane.showConfirmDialog
        (this,"Bạn có chắc muốn xoá!","Thông báo", JOptionPane.YES_NO_OPTION);
        if(choice == JOptionPane.NO_OPTION){
            return;
        }
        else{
            a.xoa(r);
            model = new DefaultTableModel();
            jTable1.setModel(model);
            model.addColumn("Mặt hàng");
            model.addColumn("Mã");
            model.addColumn("Tên hàng");
            model.addColumn("Màu");
            model.addColumn("Loại");
            model.addColumn("Năm sx");
            model.addColumn("Số lượng");
            model.addColumn("Đơn giá");
            model.addColumn("Giảm Giá");
            model.addColumn("Thành Tiền");
            for(int i=0; i<a.size(); i++){
                DienTu x=a.get(i) ;
                model.addRow(new Object[]{x.getMh(),
                    x.getMa(),x.getTen(),x.getMau(),x.getLoai(),x.getNam(),x.getSoLuong(),x.getDonGia(),x.giamGia(),x.thanhTien()});
            }
            JOptionPane.showMessageDialog(this, "Xoá thành công", "Thông báo", WIDTH);
            txt_ck.setText(""+a.tongTienGiam());
            txt_sumSL.setText(""+a.tongSoLuong());
            txt_sum.setText(""+a.tongTien());
    }//GEN-LAST:event_jButton_deleteActionPerformed
    }
    private void jButton_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_updateActionPerformed
        // TODO add your handling code here:
        StringBuilder sb = new StringBuilder();
        int index = jTable1.getSelectedRow();
        if(index==-1){
            sb.append("Vui lòng chọn 1 hàng để cập nhật \n");
        }
        if(sb.length()>0){
            JOptionPane.showMessageDialog(this, sb.toString(), "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int choice = JOptionPane.showConfirmDialog
        (this,"Bạn có muốn cập nhật!","Thông báo", JOptionPane.YES_NO_OPTION);
        if(choice == JOptionPane.NO_OPTION){
            return;
        }
        if(txt_ma.getText().equals(jTable1.getValueAt(index, 1))==false){
                    JOptionPane.showMessageDialog(this, "Không được cập nhật mã số","Thông báo", JOptionPane.ERROR_MESSAGE);
                    return;
        }
        for(int i=0;i<a.size();i++){
            if(a.get(i).getMa().equalsIgnoreCase(txt_ma.getText())){
                a.get(i).setTen(txt_ten.getText());
                a.get(i).setMau(txt_mau.getText());
                a.get(i).setLoai((String) cbx_loai.getSelectedItem());
                a.get(i).setNam (Integer.parseInt(""+cbx_nam.getSelectedItem()));
                a.get(i).setSoLuong(Integer.parseInt(txt_sl.getText()));
                a.get(i).setDonGia(Integer.parseInt(txt_dg.getText()));
                a.get(i).setMh((String) cbx_mh.getSelectedItem());       
            } 
        } 
        model = new DefaultTableModel();
        jTable1.setModel(model);
        model.addColumn("Mặt hàng");
        model.addColumn("Mã");
        model.addColumn("Tên hàng");
        model.addColumn("Màu");
        model.addColumn("Loại");
        model.addColumn("Năm sx");
        model.addColumn("Số lượng");
        model.addColumn("Đơn giá");
        model.addColumn("Giảm Giá");
        model.addColumn("Thành Tiền");
        for(int i=0; i<a.size(); i++){
            DienTu x=a.get(i);
            model.addRow(new Object[]{x.getMh(),
                x.getMa(),x.getTen(),x.getMau(),x.getLoai(),x.getNam(),x.getSoLuong(),x.getDonGia(),x.giamGia(),x.thanhTien()});
        
    }//GEN-LAST:event_jButton_updateActionPerformed
    JOptionPane.showMessageDialog(this, "Cập nhật thành công", "Thông báo", WIDTH);
    txt_ck.setText(""+a.tongTienGiam());
    txt_sumSL.setText(""+a.tongSoLuong());
    txt_sum.setText(""+a.tongTien());
    }
    private void txt_sumSLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_sumSLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_sumSLActionPerformed

    private void txt_sumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_sumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_sumActionPerformed

    private void jButton_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_refreshActionPerformed
        // TODO add your handling code here:
        txt_ma.setText("");
        txt_ten.setText("");
        txt_mau.setText("");
        txt_sl.setText("");
        txt_dg.setText("");
        txt_matk.setText("");
        txt_ma.requestFocus();
        cbx_nam.setSelectedIndex(0);
        cbx_mh.setSelectedIndex(0);
        cbx_loai.setSelectedIndex(0);
    }//GEN-LAST:event_jButton_refreshActionPerformed

    private void jButton_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_exitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton_exitActionPerformed
  
    private void jButton_findActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_findActionPerformed
        // TODO add your handling code here:
        StringBuilder sb = new StringBuilder();
        if(a.size()==0){
            JOptionPane.showMessageDialog(this, "Bản ghi đang trống", "Thông báo", JOptionPane.ERROR_MESSAGE);
            return;
        }else{
            if(txt_matk.getText().equalsIgnoreCase("")){
                sb.append("Vui lòng nhập vào ô tìm kiếm");
                txt_matk.setBackground(Color.red);
            }else txt_matk.setBackground(Color.white);
        }
        if(sb.length()>0){
            JOptionPane.showMessageDialog(this, sb.toString(),"Thông báo",JOptionPane.ERROR_MESSAGE);
            return;
        }
        DienTu dt = a.timKiem(txt_matk.getText());
        if(dt!=null){
            model.setRowCount(0);
            model.addRow(new Object[]{dt.getMh(),
               dt.getMa(),dt.getTen(),dt.getMau(),dt.getLoai(),dt.getNam(),dt.getSoLuong(),dt.getDonGia(),dt.giamGia(),dt.thanhTien()
            });  
            JOptionPane.showMessageDialog(this, "Tìm thành công", "Thông báo", WIDTH);
        }else JOptionPane.showMessageDialog(this, "Không có mã này vui lòng thử lại!", "Thông báo", JOptionPane.ERROR_MESSAGE);
        txt_matk.setText("");
        txt_matk.requestFocus();
    }//GEN-LAST:event_jButton_findActionPerformed

    private void jButton_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_saveActionPerformed
        // TODO add your handling code here:
        if(a.size()==0){
            JOptionPane.showMessageDialog(this, "Bản ghi đang trống", "Thông báo", JOptionPane.ERROR_MESSAGE);
            return;
        }
        JFileChooser fc = new JFileChooser();
        fc.setDialogTitle("Lưu File");
        fc.showSaveDialog(null);
        String tenFile = fc.getSelectedFile().getPath();
        a.ghiFile(tenFile);
        JOptionPane.showMessageDialog(this, "Lưu thành công", "Thông báo", WIDTH);
    }//GEN-LAST:event_jButton_saveActionPerformed

    private void txt_maKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_maKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyChar()==evt.VK_ENTER) txt_ten.requestFocus();
    }//GEN-LAST:event_txt_maKeyPressed

    private void txt_tenKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_tenKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyChar()==evt.VK_ENTER) txt_mau.requestFocus();
    }//GEN-LAST:event_txt_tenKeyPressed

    private void txt_mauKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_mauKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyChar()==evt.VK_ENTER) cbx_loai.requestFocus();
    }//GEN-LAST:event_txt_mauKeyPressed

    private void cbx_loaiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbx_loaiKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyChar()==evt.VK_ENTER) cbx_nam.requestFocus();
    }//GEN-LAST:event_cbx_loaiKeyPressed

    private void cbx_namKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbx_namKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyChar()==evt.VK_ENTER) txt_sl.requestFocus();
    }//GEN-LAST:event_cbx_namKeyPressed

    private void txt_slKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_slKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyChar()==evt.VK_ENTER) txt_dg.requestFocus();
    }//GEN-LAST:event_txt_slKeyPressed

    private void txt_dgKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_dgKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyChar()==evt.VK_ENTER) cbx_mh.requestFocus();
    }//GEN-LAST:event_txt_dgKeyPressed

    private void jButton_moActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_moActionPerformed
        // TODO add your handling code here:     
        JFileChooser fc = new JFileChooser();
        fc.setDialogTitle("Mở File");
        fc.showOpenDialog(null);
        String tenFile = fc.getSelectedFile().getPath();
        while(model.getRowCount()>0) model.removeRow(0);
        try {
            File f = new File(tenFile);
            if(f.exists()){
                Scanner read = new Scanner(f);
                while(read.hasNext()){
                    Scanner kb = new Scanner(read.nextLine());
                    String ma="",ten="",mau="",loai="",mh="";
                    int nam,sl,dg;
                    ma=kb.next();
                    while(!kb.hasNextInt()) ten=ten+kb.next()+" ";
                    nam=kb.nextInt();
                    while(!kb.hasNextInt()) mau=mau+kb.next()+" ";
                    sl=kb.nextInt();
                    while(!kb.hasNextInt()) loai=loai+kb.next()+" ";
                    dg=kb.nextInt();
                    while(kb.hasNext()) mh=mh+kb.next()+" ";
                    DienTu x;
                    if(mh=="Điện Thoại"){
                         x = new DienThoai(mh,ma,ten,mau,loai,nam,sl,dg);
                    }else x = new Laptop(mh,ma,ten,mau,loai,nam,sl,dg);
                    a.nhap(x);
                     model.addRow(new Object[]{x.getMh(),
            x.getMa(),x.getTen(),x.getMau(),x.getLoai(),x.getNam(),x.getSoLuong(),x.getDonGia(),x.giamGia(),x.thanhTien()});
                }
            }else System.out.println("Khong ton tai file");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_jButton_moActionPerformed

    private void jButton_xoaTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_xoaTimActionPerformed
        // TODO add your handling code here:
        model.setRowCount(0);
        for(int i=0;i<a.size();i++){
            model.addRow(new Object[]{
                a.get(i).getMh(),a.get(i).getMa(),a.get(i).getTen(),a.get(i).getMau(),
                a.get(i).getLoai(),a.get(i).getNam(),a.get(i).getSoLuong(),
                a.get(i).getDonGia(),a.get(i).giamGia(),a.get(i).thanhTien()
            });
        }
        txt_matk.setText("");
        txt_matk.requestFocus();
    }//GEN-LAST:event_jButton_xoaTimActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLBanHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLBanHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLBanHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLBanHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLBanHang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbx_loai;
    private javax.swing.JComboBox<String> cbx_mh;
    private javax.swing.JComboBox<String> cbx_nam;
    private javax.swing.JButton jButton_add;
    private javax.swing.JButton jButton_delete;
    private javax.swing.JButton jButton_exit;
    private javax.swing.JButton jButton_find;
    private javax.swing.JButton jButton_mo;
    private javax.swing.JButton jButton_refresh;
    private javax.swing.JButton jButton_save;
    private javax.swing.JButton jButton_update;
    private javax.swing.JButton jButton_xoaTim;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txt_ck;
    private javax.swing.JTextField txt_dg;
    private javax.swing.JTextField txt_ma;
    private javax.swing.JTextField txt_matk;
    private javax.swing.JTextField txt_mau;
    private javax.swing.JTextField txt_sl;
    private javax.swing.JTextField txt_sum;
    private javax.swing.JTextField txt_sumSL;
    private javax.swing.JTextField txt_ten;
    // End of variables declaration//GEN-END:variables
}
